/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaestudiantes;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author jose99
 */
public class Estudiantes extends java.awt.Frame {

    /**
     * Creates new form Estudiantes
     */
    public Estudiantes() {
        initComponents();
    }
@SuppressWarnings("unchechek")
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txthabilidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbestudiantes = new javax.swing.JTable();
        btneditar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setText("Nombre");

        txtNombre.setText("");

        jLabel2.setText("Apellido");

        txtApellido.setText("");
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });

        jLabel3.setText("Correo");

        txtCorreo.setText("");

        jLabel4.setText("habilidad");

        txthabilidad.setText("");

        jLabel5.setText("telefono");

        txttelefono.setText("");

        btnguardar.setText("Guardar");

        tbestudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbestudiantes);

        btneditar.setText("Editar");

        btneliminar.setText("Borrar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(txtApellido)
                            .addComponent(txtCorreo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txthabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnguardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btneditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btneliminar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txthabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(btneditar)
                    .addComponent(btneliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(256, 256, 256))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Limpiar campos
    public void limpiar(){

        txtNombre.setText("");
                txtApellido.setText("");
        txtCorreo.setText("");
        txthabilidad.setText("");
        txttelefono.setText("");

    }
    //Imprimir registros en la tabla
    public void imprimir(){

        try{
conectar = Conectar.getConnection();
String [] alumnos = {"id","Nombre","Apellido","Correo","habilidad","telefono"};

model = new DefaultTableModel(null,alumnos);
sent = conectar.createStatement();
Resulset rs = sent.executeQuery("SELECT * FROM descrip_estudiantes");
String fila []= new String [6];
while (rs.next()) {
    
    fila[0]= rs.getString("id");
        fila[1]= rs.getString("Nombre");
    fila[2]= rs.getString("Apellido");
    fila[3]= rs.getString("Correo");
    fila[4]= rs.getString("habilidad");
    fila[5]= rs.getString("telefono");
model.addRow(fila);
}
tbestudiantes.setModel(model);
        }catch (SQLException e){
    e.printStackTrace();

    }
    }
    // Guardar registros de estudiantes

private void btnguardarActionPerformed(java.awt.event.ActionEvent evt){
    try{
        PreparedStatement pat = cn.prepareCall("INSERT INTO descrip_estudiantes (Nombre,Apellido,Correo,habilidad,telefono) VALUES (?,?,?,?,?)");
    pat.setString(1, txtNombre.getText());
     pat.setString(2, txtApellido.getText());
      pat.setString(3, txtCorreo.getText());
       pat.setString(4, txthabilidad.getText());
        pat.setString(5, txttelefono.getText());
        int n =pat.executeUpdate();
        if(n>0){
            JOptionPane.showMessageDialog(null,"Datos guardados.");
        }
    } catch (SQLException e){
    JOptionPane.showMessageDialog(null,"error. "+e.getMessage());
    }
    }

// Modificar datos de estudiante
private void btneditarActionPerformed(java.awt.event.ActionEvent evt){
try{

    int fila = tbestudiantes.getSelectedRow();
    String dao = (String)tbestudiantes.getValueAt(fila,0);
PreparedStatement pat = cn.prepareCall("UPDATE descrip_estudiantes SET Nombre=?,Apellido=?,Correo=?,habilidad=?,telefono=? WHERE id=?");
pat.setString(1, txtNombre.getText());
     pat.setString(2, txtApellido.getText());
      pat.setString(3, txtCorreo.getText());
       pat.setString(4, txthabilidad.getText());
        pat.setString(5, txttelefono.getText());
        pat.setString(6,dao);//La llamada SQL se muestra en la tabla
        int n =pat.executeUpdate();
        if(n>0){
            limpiar();
            imprimir();
            JOptionPane.showMessageDialog(null,"Datos modificados.");
        }
}catch (SQLException e){
    JOptionPane.showMessageDialog(null,"error. "+e.getMessage());
    }


}
// Eliminar estudiantes
private void btneliminarActionPerformed(java.awt.event.ActionEvent evt){

    try{
int fila = tbestudiantes.getSelectedRow();
sent = cn.createStatement();
int n = sent.executeUpdate("DELETE FROM  descrip_estudiantes WHERE id= "+tbestudiantes.getValueAt(fila,0));
    if (n > 0) {
        imprimir();
       JOptionPane.showMessageDialog(null,"Datos eliminados."); 
       limpiar();
    }

    } catch (SQLException e){
    JOptionPane.showMessageDialog(null,"error. "+e.getMessage());
    }
} 
    /**
     * Exit the Application
     Salir de la aplicacion
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    /**
     * @param args the command line arguments
     */
    //Codigo para ejecutar el codigo en una ventana
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new Estudiantes().setVisible(true);
        });
    }

//Declaracion de variables
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbestudiantes;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txthabilidad;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables

  //Conexion con base de datos Mysql
Conectar cc = new Conectar();
    Connection cn = cc.conexion();
}
